config/routes.rb
Depot::Application.routes.draw do
  resources :faqs

  resources :contacts

  resources :news

  resources :line_items

  resources :carts

  get "store/index"

  resources :products

root to: 'store#index', as: 'store'

match ':controller(/:action(/:id))(.:format)'
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faqs }
    end
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
    @faq = Faq.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/new
  # GET /faqs/new.json
  def new
    @faq = Faq.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @faq }
    end
  end

  # GET /faqs/1/edit
  def edit
    @faq = Faq.find(params[:id])
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(params[:faq])

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render json: @faq, status: :created, location: @faq }
      else
        format.html { render action: "new" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /faqs/1
  # PUT /faqs/1.json
  def update
    @faq = Faq.find(params[:id])

    respond_to do |format|
      if @faq.update_attributes(params[:faq])
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy

    respond_to do |format|
      format.html { redirect_to faqs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_form.html.erb
<%= form_for(@faq) do |f| %>
  <% if @faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

      <ul>
      <% @faq.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing faq</h1>

<%= render 'form' %>

<%= link_to 'Show', @faq %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<h1>Listing faqs</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @faqs.each do |faq| %>
  <tr>
    <td><%= link_to 'Show', faq %></td>
    <td><%= link_to 'Edit', edit_faq_path(faq) %></td>
    <td><%= link_to 'Destroy', faq, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Faq', new_faq_path %>

app/views/faqs/new.html.erb
<h1>New faq</h1>

<%= render 'form' %>

<%= link_to 'Back', faqs_path %>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>