config/routes.rb
Depot::Application.routes.draw do
  resources :faqs

  resources :contacts

  resources :news

  resources :line_items

  resources :carts

  get "store/index"

  resources :products

root to: 'store#index', as: 'store'

match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
<!-- START_HIGHLIGHT -->
  <title>Toasty Toes Furry Socks</title>
<!-- END_HIGHLIGHT -->
  <%= stylesheet_link_tag    "application", media: "all" %><!-- <label id="code.slt"/> -->
  <%= javascript_include_tag "application" %><!-- <label id="code.jlt"/> -->
  <%= csrf_meta_tags %><!-- <label id="code.csrf"/> -->
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
<!-- START_HIGHLIGHT -->
  <div id="banner">
    <%= link_to image_tag("logo.jpeg"), store_path %>
    <%= @page_title || "Toasty Toes" %><!-- <label id="code.depot.e.title"/> -->
  </div>
  <div id="banner_subtitle">
    <%= @page_subtitle || "Furry Socks for EVERY Occasion." %>
  </div>
  <div id="columns">
    <div id="side">
      <ul>
        <li><%= link_to 'Home', store_path %> </li> 
        <li><%= link_to 'FAQ', faqs_path %> </li>
        <li><%= link_to 'News', news_index_path %> </li>  
        <li><%= link_to 'Contact', contacts_path %> </li> 
      </ul>
    </div>
    <div id="main">
<!-- END_HIGHLIGHT -->
      <%= yield %><!-- <label id="code.depot.e.include"/> -->
<!-- START_HIGHLIGHT -->
    </div>
  </div>
<!-- END_HIGHLIGHT -->
</body>
</html>